# Generated by Django 2.1.7 on 2019-03-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(choices=[('SG', 'Sugestões'), ('CT', 'Críticas'), ('DV', 'Diverso')], default='SG', max_length=2)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
