# Generated by Django 2.1.7 on 2019-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato_page', '0002_auto_20190306_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.TextField(default='Anonimo', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(blank=True, default='Anonimo', max_length=40),
        ),
    ]
